/**
 * In-process hourly cron that nags debtors when their debts are overdue.
 *
 * Strategy:
 *   - Scan once on startup.
 *   - Then setInterval every 60 minutes.
 *   - Push at most ONE reminder per debt per 24h (lastRemindedAt).
 *   - Reminder text is generated by ตุ๊ต๊ะ (mode 3/4/5 based on overdue days)
 *     — never templated, no fallback string.
 */
import { prisma } from '@/lib/prisma'
import { lineClient } from '@/lib/line'
import { generateEventReply } from '@/lib/bot/secretary'

const SCAN_INTERVAL_MS = 60 * 60 * 1000 // 1h
const MIN_REMINDER_GAP_MS = 24 * 60 * 60 * 1000 // 24h
const MS_PER_DAY = 24 * 60 * 60 * 1000
const SATANG_PER_BAHT = 100

interface CronLogger {
  info: (obj: unknown, msg?: string) => void
  warn: (obj: unknown, msg?: string) => void
}

export function startReminderCron(log: CronLogger): void {
  // Run once on boot, then on interval.
  void runScan(log)
  setInterval(() => {
    void runScan(log)
  }, SCAN_INTERVAL_MS)
}

async function runScan(log: CronLogger): Promise<void> {
  const now = new Date()
  try {
    const overdue = await prisma.debtRequest.findMany({
      where: {
        status: 'pending',
        dueAt: { lt: now },
      },
      include: {
        debtor: { select: { id: true, lineUserId: true, displayName: true } },
        creditor: { select: { displayName: true } },
      },
    })
    if (overdue.length === 0) {
      log.info({ at: now.toISOString() }, 'reminder.cron.empty')
      return
    }
    let pushed = 0
    for (const d of overdue) {
      if (
        d.lastRemindedAt &&
        now.getTime() - d.lastRemindedAt.getTime() < MIN_REMINDER_GAP_MS
      ) {
        continue
      }
      const ok = await pushReminder(d, now, log)
      if (ok) pushed += 1
    }
    log.info({ scanned: overdue.length, pushed }, 'reminder.cron.done')
  } catch (err) {
    log.warn({ err }, 'reminder.cron.failed')
  }
}

interface OverdueRow {
  id: string
  amount: number
  reason: string | null
  dueAt: Date | null
  reminderCount: number
  debtor: { id: string; lineUserId: string; displayName: string }
  creditor: { displayName: string }
}

async function pushReminder(d: OverdueRow, now: Date, log: CronLogger): Promise<boolean> {
  if (!d.dueAt) return false
  const overdueDays = Math.max(1, Math.floor((now.getTime() - d.dueAt.getTime()) / MS_PER_DAY))
  const amountBaht = (d.amount / SATANG_PER_BAHT).toLocaleString('en-US', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })
  const reasonClause = d.reason ? `เหตุ: ${d.reason}` : 'ไม่มีระบุเหตุ'
  // Hint which of modes 3/4/5 to pick. The persona prompt
  // already encodes the mode rules — we just describe the situation.
  const instruction = `เตือนผู้ใช้ว่าหนี้ค้าง ฿${amountBaht} ที่ติด ${d.creditor.displayName} (${reasonClause}) เลยกำหนดมา ${overdueDays} วัน นี่เป็นการทวงครั้งที่ ${d.reminderCount + 1} เลือกโหมด 3/4/5 ตามจำนวนวันที่เลย ทักเป็นข้อความเดียวสั้นๆ ไม่ต้องถาม`
  const text = await generateEventReply(d.debtor.id, instruction, log)
  if (!text) {
    log.warn({ debtId: d.id }, 'reminder.cron.gemini.empty')
    return false
  }

  try {
    await lineClient.pushMessage({
      to: d.debtor.lineUserId,
      messages: [{ type: 'text', text }],
    })
    await prisma.debtRequest.update({
      where: { id: d.id },
      data: { reminderCount: { increment: 1 }, lastRemindedAt: now },
    })
    return true
  } catch (err) {
    log.warn({ err, debtId: d.id }, 'reminder.cron.push.failed')
    return false
  }
}
